openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-14
    description: 'Public web api'
paths:
  /api/message:
    post:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /register:
    post:
      summary: Build a building
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                birthDay:
                  type: string
                adress:
                  type: string
                number:
                  type: string
                dome:
                  type: string
                crop1:
                  type: string
                crop2:
                  type: string
                crop3:
                  type: string
              required:
                - firstname
                - lastname
                - email
                - birthDay
                - adress
                - number
                - dome
                - crop1
                - crop2
                - crop3
      responses:
        200:
          description: Ok