openapi: 3.0.0
info:
  title: 'Mars Concept Title'
  description: 'Please complete this spec as seen in the module Information Module'
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: 'Local development implementation'
  - url: https://project-ii.ti.howest.be/mars-14
    description: 'Public web api'

components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
          example: "John"
        lastname:
          type: string
          example: "Doe"
        email:
          type: string
          example: "John.Doe@gmail.com"
        birthDay:
          type: string
          example: "01-01-2000"
        address:
          type: string
          example: "The Moon"
        number:
          type: number
          example: 1234567890
        dome:
          type: string
          example: "1337"
        crop1:
          type: string
          example: "Apple"
        crop2:
          type: string
          example: "Carrot"
        crop3:
          type: string
          example: "Raspberry Pi"

    Product:
      type: object
      properties:
        id:
          type: "integer"
          example: 1
        name:
          type: "string"
          example: "Alice"
        price:
          type: "number"
          example: 5
        ownerId:
          type: "number"
          example: 1
        date:
          type: "string"
          example: "01-01-2000"
        amount:
          type: "integer"
          example: 10
        image:
          type: "string"
          example: "picture.png"
        type:
          type: "string"
          enum: ["seed", "plant"]
          default: "plant"
          example: "plant"



paths:
  /api/message:
    get:
      description: Get a nice message
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /register:
    post:
      summary: create new user
      operationId: createUser
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              items:
                $ref: "#/components/schemas/User"
      responses:
        '200':
          description: Ok
        '401':
          description: Absent or mallformed authentication
        '500':
          description: Internal Server Error


  /getPlants:
    get:
      summary: Get all plants
      operationId: getPlants
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Absent or mallformed authentication
        '500':
          description: Internal Server Error

  /getSeeds:
    get:
      summary: Get all Seeds
      operationId: getSeeds
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Absent or mallformed authentication
        '500':
          description: Internal Server Error

  /addProduct:
    post:
      summary: Add new product
      operationId: addProduct
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              items:
                $ref: '#/components/schemas/Product'

      responses:
        '200':
          description: OK
        '401':
          description: Absent or mallformed authentication
        '500':
          description: Internal Server Error

  /product/{productId}:
    delete:
      summary: remove a product
      operationId: removeProduct
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Invalid Authentication
        '500':
          description: Internal Server Error


  /addProductToFavorite/{productId}:
    get:
      summary: Add a product to you favorits
      operationId: addProductToFavorite
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Invalid Authentication
        '500':
          description: Internal Server Error

  /addProcuctToBasket/{productId}:
    get:
      summary: Add a product to your basket
      operationId: AddProductToBasket
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Invalid Authentication
        '500':
          description: Internal Server Error